# Generated by Django 5.2 on 2026-07-20 19:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Parte')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Componente')),
                ('category', models.CharField(choices=[('PNL', 'Panel (LCD/OLED)'), ('MB', 'Main Board (Tarjeta Principal)'), ('PWR', 'Power Supply (Fuente de Poder)'), ('BZL', 'Bezel / Chasis'), ('PKG', 'Empaque y Cartón'), ('ACC', 'Accesorios (Control, Cables, Pedestal)')], default='ACC', max_length=3, verbose_name='Categoría')),
                ('safety_stock', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Stock de Seguridad Mínimo')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Modelo')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU / Código Único')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción Técnica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto (Televisor)',
                'verbose_name_plural': 'Productos (Televisores)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='Stock Físico Actual')),
                ('in_transit_stock', models.PositiveIntegerField(default=0, verbose_name='Stock en Tránsito')),
                ('warehouse_location', models.CharField(max_length=50, verbose_name='Ubicación en Almacén (Rack/Bin)')),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='materials.component')),
            ],
            options={
                'verbose_name': 'Inventario de Componente',
                'verbose_name_plural': 'Inventarios de Componentes',
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Requerida')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_relations', to='materials.component')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_relations', to='materials.product')),
            ],
            options={
                'verbose_name': 'Componente de BOM',
                'verbose_name_plural': 'Componentes de BOM',
                'unique_together': {('product', 'component')},
            },
        ),
    ]
